EQueue/EQueue.AdminWeb/Controllers/BrokerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using EQueue.AdminWeb.Models;

namespace EQueue.AdminWeb.Controllers
{
    [HandleError]
    public class BrokerController : Controller
    {
        private MessageService _messageService;

        public BrokerController(MessageService messageService)
        {
            _messageService = messageService;
        }

        public ActionResult Index(string clusterName, string brokerName)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var result = _messageService.QueryBrokerStatisticInfo(clusterName, brokerName);
            return View(result);
        }
        public ActionResult QueueInfoList(string clusterName, string brokerName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var topicQueueInfoList = _messageService.GetTopicQueueInfoList(clusterName, brokerName, topic);
            return View(new BrokerTopicQueueListViewModel
            {
                Topic = topic,
                TopicQueueInfoList = topicQueueInfoList
            });
        }
        public ActionResult ConsumeInfoList(string clusterName, string brokerName, string group, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var topicConsumeInfoList = _messageService.GetTopicConsumeInfoList(clusterName, brokerName, group, topic);
            return View(new BrokerTopicConsumeListViewModel
            {
                Group = group,
                Topic = topic,
                TopicConsumeInfoList = topicConsumeInfoList
            });
        }
        public ActionResult ProducerList(string clusterName, string brokerName, string group, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var producerList = _messageService.GetProducerInfoList(clusterName, brokerName);
            return View(new BrokerProducerListViewModel
            {
                ProducerList = producerList
            });
        }
        public ActionResult ConsumerList(string clusterName, string brokerName, string group, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var consumerList = _messageService.GetConsumerInfoList(clusterName, brokerName, group, topic);
            return View(new BrokerConsumerListViewModel
            {
                Group = group,
                Topic = topic,
                ConsumerList = consumerList
            });
        }
        public ActionResult LatestSendMessages(string clusterName, string brokerName)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var messageList = _messageService.GetLatestSendMessagesList(clusterName, brokerName);
            var messageInfoList = new List<MessageInfo>();

            foreach (var message in messageList)
            {
                string[] array = message.Split('_');
                var messageId = array[0];
                var createTime = new DateTime(long.Parse(array[1]));
                var storedTime = new DateTime(long.Parse(array[2]));
                messageInfoList.Add(new MessageInfo
                {
                    MessageId = messageId,
                    CreateTime = createTime,
                    StoredTime = storedTime
                });
            }
            messageInfoList.Sort((x, y) =>
            {
                if (x.StoredTime.Ticks > y.StoredTime.Ticks)
                {
                    return -1;
                }
                else if (x.StoredTime.Ticks < y.StoredTime.Ticks)
                {
                    return 1;
                }
                return 0;
            });

            var sequence = 1;
            foreach (var messageInfo in messageInfoList)
            {
                messageInfo.Sequence = sequence++;
            }
            return View(new BrokerLatestMessageIdListViewModel
            {
                MessageInfoList = messageInfoList
            });
        }
        public ActionResult CreateTopic(string clusterName, string brokerName, string topic, int? initialQueueCount)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            _messageService.CreateTopic(clusterName, brokerName, topic, initialQueueCount ?? 4);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public ActionResult DeleteTopic(string clusterName, string brokerName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            _messageService.DeleteTopic(clusterName, brokerName, topic);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public ActionResult AddQueue(string clusterName, string brokerName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            _messageService.AddQueue(clusterName, brokerName, topic);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public ActionResult DeleteQueue(string clusterName, string brokerName, string topic, int queueId)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            _messageService.DeleteQueue(clusterName, brokerName, topic, queueId);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public ActionResult SetQueueProducerVisible(string clusterName, string brokerName, string topic, int queueId, bool visible)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            _messageService.SetQueueProducerVisible(clusterName, brokerName, topic, queueId, visible);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        public ActionResult SetQueueConsumerVisible(string clusterName, string brokerName, string topic, int queueId, bool visible)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            _messageService.SetQueueConsumerVisible(clusterName, brokerName, topic, queueId, visible);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Topic = topic });
        }
        [HttpGet]
        public ActionResult SetQueueNextConsumeOffset(string clusterName, string brokerName, string consumerGroup, string topic, int queueId)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            var model = new SetQueueNextConsumeOffsetViewModel
            {
                ConsumerGroup = consumerGroup,
                Topic = topic,
                QueueId = queueId
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult SetQueueNextConsumeOffset(string clusterName, string brokerName, string consumerGroup, string topic, int queueId, long nextOffset)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            _messageService.SetQueueNextConsumeOffset(clusterName, brokerName, consumerGroup, topic, queueId, nextOffset);
            return RedirectToAction("ConsumeInfoList", new { ClusterName = clusterName, BrokerName = brokerName, Group = consumerGroup, Topic = topic });
        }
        public ActionResult DeleteConsumerGroup(string clusterName, string brokerName, string consumerGroup)
        {
            ViewBag.ClusterName = clusterName;
            ViewBag.BrokerName = brokerName;
            _messageService.DeleteConsumerGroup(clusterName, brokerName, consumerGroup);
            return RedirectToAction("ConsumeInfoList", new { ClusterName = clusterName, BrokerName = brokerName });
        }
    }
}

EQueue/EQueue.AdminWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Web.Mvc;
using EQueue.AdminWeb.Models;
using EQueue.Utils;

namespace EQueue.AdminWeb.Controllers
{
    [HandleError]
    public class HomeController : Controller
    {
        private MessageService _messageService;

        public HomeController(MessageService messageService)
        {
            _messageService = messageService;
        }

        public ActionResult Index()
        {
            var clusterList = _messageService.GetAllClusters();
            return View(new ClusterListViewModel
            {
                ClusterList = clusterList
            });
        }
        public ActionResult BrokerList(string clusterName)
        {
            ViewBag.ClusterName = clusterName;
            var brokerList = _messageService.GetClusterBrokerStatusInfoList(clusterName);
            return View(new ClusterBrokerListViewModel
            {
                BrokerList = brokerList
            });
        }
        public ActionResult QueueInfoList(string clusterName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            var topicQueueInfoList = _messageService.GetTopicQueueInfoList(clusterName, topic);
            return View(new ClusterTopicQueueListViewModel
            {
                Topic = topic,
                TopicQueueInfoList = topicQueueInfoList
            });
        }
        public ActionResult ConsumeInfoList(string clusterName, string group, string topic)
        {
            ViewBag.ClusterName = clusterName;
            var topicConsumeInfoList = _messageService.GetTopicConsumeInfoList(clusterName, group, topic);
            return View(new ClusterTopicConsumeListViewModel
            {
                Group = group,
                Topic = topic,
                TopicConsumeInfoList = topicConsumeInfoList
            });
        }
        public ActionResult ProducerList(string clusterName)
        {
            ViewBag.ClusterName = clusterName;
            var producerList = _messageService.GetProducerInfoList(clusterName);
            return View(new ClusterProducerListViewModel
            {
                ProducerList = producerList
            });
        }
        public ActionResult ConsumerList(string clusterName, string group, string topic)
        {
            ViewBag.ClusterName = clusterName;
            var consumerInfoList = _messageService.GetConsumerInfoList(clusterName, group, topic);
            var modelList = new List<ConsumerViewModel>();
            foreach (var consumerInfo in consumerInfoList)
            {
                foreach (var consumer in consumerInfo.ConsumerList)
                {
                    modelList.Add(new ConsumerViewModel
                    {
                        BrokerInfo = consumerInfo.BrokerInfo,
                        ConsumerInfo = consumer
                    });
                }
            }
            modelList.Sort((x, y) =>
            {
                var result = string.Compare(x.ConsumerInfo.ConsumerGroup, y.ConsumerInfo.ConsumerGroup);
                if (result != 0)
                {
                    return result;
                }
                result = string.Compare(x.ConsumerInfo.ConsumerId, y.ConsumerInfo.ConsumerId);
                if (result != 0)
                {
                    return result;
                }
                result = string.Compare(x.BrokerInfo.BrokerName, y.BrokerInfo.BrokerName);
                if (result != 0)
                {
                    return result;
                }
                result = string.Compare(x.ConsumerInfo.Topic, y.ConsumerInfo.Topic);
                if (result != 0)
                {
                    return result;
                }
                if (x.ConsumerInfo.QueueId > y.ConsumerInfo.QueueId)
                {
                    return 1;
                }
                else if (x.ConsumerInfo.QueueId < y.ConsumerInfo.QueueId)
                {
                    return -1;
                }
                return 0;
            });
            return View(new ClusterConsumerListViewModel
            {
                Group = group,
                Topic = topic,
                ConsumerList = modelList
            });
        }
        public ActionResult Message(string clusterName, string searchMessageId)
        {
            ViewBag.ClusterName = clusterName;
            if (string.IsNullOrWhiteSpace(searchMessageId))
            {
                return View(new MessageViewModel());
            }
            MessageIdInfo messageIdInfo;
            try
            {
                messageIdInfo = MessageIdUtil.ParseMessageId(searchMessageId);
            }
            catch (Exception ex)
            {
                throw new Exception("无效的消息ID", ex);
            }
            var message = _messageService.GetMessageDetail(clusterName, searchMessageId);
            var model = new MessageViewModel { ClusterName = clusterName, SearchMessageId = searchMessageId };
            if (message != null)
            {
                model.ProducerAddress = message.ProducerAddress;
                model.BrokerAddress = messageIdInfo.IP.ToString() + ":" + messageIdInfo.Port.ToString();
                model.MessageId = message.MessageId;
                model.Topic = message.Topic;
                model.QueueId = message.QueueId.ToString();
                model.QueueOffset = message.QueueOffset.ToString();
                model.Code = message.Code.ToString();
                model.Payload = Encoding.UTF8.GetString(message.Body);
                model.CreatedTime = message.CreatedTime.ToString("yyyy-MM-dd HH:mm:ss.fff");
                model.StoredTime = message.StoredTime.ToString("yyyy-MM-dd HH:mm:ss.fff");
            }
            return View(model);
        }
        public ActionResult CreateTopic(string clusterName, string topic, int? initialQueueCount)
        {
            ViewBag.ClusterName = clusterName;
            _messageService.CreateTopic(clusterName, topic, initialQueueCount ?? 4);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, Topic = topic });
        }
        public ActionResult DeleteTopic(string clusterName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            _messageService.DeleteTopic(clusterName, topic);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, Topic = topic });
        }
        public ActionResult AddQueue(string clusterName, string topic)
        {
            ViewBag.ClusterName = clusterName;
            _messageService.AddQueue(clusterName, topic);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, Topic = topic });
        }
        public ActionResult DeleteQueue(string clusterName, string topic, int queueId)
        {
            ViewBag.ClusterName = clusterName;
            _messageService.DeleteQueue(clusterName, topic, queueId);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, Topic = topic });
        }
        public ActionResult SetQueueProducerVisible(string clusterName, string topic, int queueId, bool visible)
        {
            ViewBag.ClusterName = clusterName;
            _messageService.SetQueueProducerVisible(clusterName, topic, queueId, visible);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, Topic = topic });
        }
        public ActionResult SetQueueConsumerVisible(string clusterName, string topic, int queueId, bool visible)
        {
            ViewBag.ClusterName = clusterName;
            _messageService.SetQueueConsumerVisible(clusterName, topic, queueId, visible);
            return RedirectToAction("QueueInfoList", new { ClusterName = clusterName, Topic = topic });
        }
        [HttpGet]
        public ActionResult SetQueueNextConsumeOffset(string clusterName, string consumerGroup, string topic, int queueId)
        {
            ViewBag.ClusterName = clusterName;
            var model = new SetQueueNextConsumeOffsetViewModel
            {
                ConsumerGroup = consumerGroup,
                Topic = topic,
                QueueId = queueId
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult SetQueueNextConsumeOffset(string clusterName, string consumerGroup, string topic, int queueId, long nextOffset)
        {
            ViewBag.ClusterName = clusterName;
            _messageService.SetQueueNextConsumeOffset(clusterName, consumerGroup, topic, queueId, nextOffset);
            return RedirectToAction("ConsumeInfoList", new { ClusterName = clusterName, Group = consumerGroup, Topic = topic });
        }
        public ActionResult DeleteConsumerGroup(string clusterName, string consumerGroup)
        {
            ViewBag.ClusterName = clusterName;
            _messageService.DeleteConsumerGroup(clusterName, consumerGroup);
            return RedirectToAction("ConsumeInfoList", new { ClusterName = clusterName });
        }
    }
}

EQueue/EQueue.AdminWeb/Views/Home/BrokerList.cshtml
@model EQueue.AdminWeb.Models.ClusterBrokerListViewModel
@{
    ViewBag.Title = "BrokerList";
}
<div>
    @using (Html.BeginForm("BrokerList", "Home", new { clusterName = ViewBag.ClusterName, brokerName = ViewBag.BrokerName }, FormMethod.Post, new { @class = "form-inline", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="13%" class="vertical-center">
                    GroupName
                </th>
                <th width="13%" class="vertical-center">
                    BrokerName
                </th>
                <th width="8%" class="vertical-center">
                    BrokerRole
                </th>
                <th width="12%" class="vertical-center">
                    ProducerAddress
                </th>
                <th width="12%" class="vertical-center">
                    ConsumerAddress
                </th>
                <th width="12%" class="vertical-center">
                    AdminAddress
                </th>
                <th width="7%" class="vertical-center">
                    发送TPS
                </th>
                <th width="7%" class="vertical-center">
                    消费TPS
                </th>
                <th width="10%" class="vertical-center">
                    总堆积数
                </th>
                <th width="8%" class="vertical-center">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.BrokerList)
            {
                var broker = item.BrokerInfo;
                <tr>
                    <td class="vertical-center">
                        @broker.GroupName
                    </td>
                    <td class="vertical-center">
                        @broker.BrokerName
                    </td>
                    <td class="vertical-center">
                        @broker.BrokerRole
                    </td>
                    <td class="vertical-center">
                        @broker.ProducerAddress
                    </td>
                    <td class="vertical-center">
                        @broker.ConsumerAddress
                    </td>
                    <td class="vertical-center">
                        @broker.AdminAddress
                    </td>
                    <td class="vertical-center">
                        @item.TotalSendThroughput
                    </td>
                    <td class="vertical-center">
                        @item.TotalConsumeThroughput
                    </td>
                    <td class="vertical-center">
                        @item.TotalUnConsumedMessageCount
                    </td>
                    <td class="vertical-center">
                        @Html.ActionLink("查看", "Index", "Broker", new { clusterName = broker.ClusterName, brokerName = broker.BrokerName }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

EQueue/EQueue.AdminWeb/Views/Home/ConsumeInfoList.cshtml
@model EQueue.AdminWeb.Models.ClusterTopicConsumeListViewModel
@{
    ViewBag.Title = "ConsumeInfoList";
}
<div>
    @using (Html.BeginForm("ConsumeInfoList", "Home", new { clusterName = ViewBag.ClusterName }, FormMethod.Post, new { @class = "form-inline", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Group"></label>
            @Html.TextBoxFor(m => m.Group, new { @class = "form-control", placeholder = "Group" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Topic"></label>
            @Html.TextBoxFor(m => m.Topic, new { @class = "form-control", placeholder = "Topic" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="10%" class="vertical-center">
                    BrokerName
                </th>
                <th width="10%" class="vertical-center">
                    ConsumerGroup
                </th>
                <th width="10%" class="vertical-center">
                    Topic
                </th>
                <th width="5%" class="text-center vertical-center">
                    QueueId
                </th>
                <th width="10%" class="text-center vertical-center">
                    CurrentOffset
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费进度
                </th>
                <th width="10%" class="text-center vertical-center">
                    堆积数
                </th>
                <th width="10%" class="text-center vertical-center">
                    CacheCount
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费者个数
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费TPS
                </th>
                <th width="5%" class="vertical-center">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.TopicConsumeInfoList)
            {
                foreach (var item in line.TopicConsumeInfoList)
                {
                    <tr>
                        <td class="vertical-center">
                            @Html.ActionLink(@line.BrokerInfo.BrokerName, "Index", "Broker", new { clusterName = ViewBag.ClusterName, brokerName = @line.BrokerInfo.BrokerName }, null)
                        </td>
                        <td class="vertical-center">
                            @item.ConsumerGroup
                        </td>
                        <td class="vertical-center">
                            @item.Topic
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueId
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueCurrentOffset
                        </td>
                        <td class="text-center vertical-center">
                            @item.ConsumedOffset
                        </td>
                        <td class="text-center vertical-center">
                            @item.QueueNotConsumeCount
                        </td>
                        <td class="text-center vertical-center">
                            @item.ClientCachedMessageCount
                        </td>
                        <td class="text-center vertical-center">
                            @item.OnlineConsumerCount
                        </td>
                        <td class="text-center vertical-center">
                            @item.ConsumeThroughput
                        </td>
                        <td class="vertical-center">
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                                    操作
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("设置队列消费进度", "SetQueueNextConsumeOffset", new { clusterName = ViewBag.ClusterName, consumerGroup = item.ConsumerGroup, topic = item.Topic, queueId = item.QueueId })
                                    </li>
                                    @if (item.OnlineConsumerCount == 0)
                                    {
                                        <li>
                                            @Html.ActionLink("删除消费者分组", "DeleteConsumerGroup", new { clusterName = ViewBag.ClusterName, consumerGroup = item.ConsumerGroup })
                                        </li>
                                    }
                                </ul>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

EQueue/EQueue.AdminWeb/Views/Home/ConsumerList.cshtml
@model EQueue.AdminWeb.Models.ClusterConsumerListViewModel
@{
    ViewBag.Title = "ConsumerList";
}
<div>
    @using (Html.BeginForm("ConsumerList", "Home", new { clusterName = ViewBag.ClusterName }, FormMethod.Post, new { @class = "form-inline", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Group"></label>
            @Html.TextBoxFor(m => m.Group, new { @class = "form-control", placeholder = "Group" })
        </div>
        <div class="form-group">
            <label class="sr-only" for="Topic"></label>
            @Html.TextBoxFor(m => m.Topic, new { @class = "form-control", placeholder = "Topic" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="10%" class="vertical-center">
                    ConsumerGroup
                </th>
                <th width="20%" class="vertical-center">
                    ConsumerId
                </th>
                <th width="10%" class="vertical-center">
                    BrokerName
                </th>
                <th width="10%" class="vertical-center">
                    Topic
                </th>
                <th width="10%" class="text-center vertical-center">
                    QueueId
                </th>
                <th width="10%" class="text-center vertical-center">
                    CurrentOffset
                </th>
                <th width="10%" class="text-center vertical-center">
                    消费进度
                </th>
                <th width="10%" class="text-center vertical-center">
                    堆积数
                </th>
                <th width="10%" class="text-center vertical-center">
                    CacheCount
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ConsumerList)
            {
                <tr>
                    <td class="vertical-center">
                        @item.ConsumerInfo.ConsumerGroup
                    </td>
                    <td class="vertical-center">
                        @item.ConsumerInfo.ConsumerId
                    </td>
                    <td class="vertical-center">
                        @Html.ActionLink(@item.BrokerInfo.BrokerName, "Index", "Broker", new { clusterName = ViewBag.ClusterName, brokerName = @item.BrokerInfo.BrokerName }, null)
                    </td>
                    <td class="vertical-center">
                        @item.ConsumerInfo.Topic
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.QueueId
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.QueueCurrentOffset
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.ConsumedOffset
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.QueueNotConsumeCount
                    </td>
                    <td class="text-center vertical-center">
                        @item.ConsumerInfo.ClientCachedMessageCount
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

EQueue/EQueue.AdminWeb/Views/Home/ProducerList.cshtml
@model EQueue.AdminWeb.Models.ClusterProducerListViewModel
@{
    ViewBag.Title = "ProducerList";
}
<div>
    @using (Html.BeginForm("ProducerList", "Home", new { clusterName = ViewBag.ClusterName }, FormMethod.Post, new { @class = "form-inline header-form", role = "form" }))
    {
        <div class="form-group">
            <label class="sr-only" for="ClusterName"></label>
            @Html.TextBoxFor(m => m.ClusterName, new { @class = "form-control", placeholder = "ClusterName" })
        </div>
        <button type="submit" class="btn btn-default">查询</button>
    }
    <table class="table table-striped">
        <thead>
            <tr>
                <th width="20%" class="vertical-center">
                    BrokerName
                </th>
                <th width="80%" class="vertical-center">
                    ProducerId
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ProducerList)
            {
                foreach (var item in line.ProducerList)
                {
                    <tr>
                        <td class="vertical-center">
                            @Html.ActionLink(@line.BrokerInfo.BrokerName, "Index", "Broker", new { clusterName = ViewBag.ClusterName, brokerName = @line.BrokerInfo.BrokerName }, null)
                        </td>
                        <td class="vertical-center">
                            @item
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>