Forum.Web/Controllers/PostController.cs
using System.Linq;
using System.Threading.Tasks;
using ECommon.IO;
using ECommon.Utilities;
using ENode.Commanding;
using Forum.Commands.Posts;
using Forum.QueryServices;
using Forum.QueryServices.DTOs;
using Forum.Web.Controls;
using Forum.Web.Extensions;
using Forum.Web.Models;
using Forum.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Forum.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly ICommandService _commandService;
        private readonly IPostQueryService _postQueryService;
        private readonly IContextService _contextService;
        private readonly ISectionQueryService _sectionQueryService;

        public PostController(ICommandService commandService, IPostQueryService queryService, IContextService contextService, ISectionQueryService sectionqueryService)
        {
            _commandService = commandService;
            _postQueryService = queryService;
            _contextService = contextService;
            _sectionQueryService = sectionqueryService;
        }

        [HttpGet]
        public ActionResult Index(string sectionId, string authorId, int? page)
        {
            var pageIndex = page == null ? 1 : page.Value;
            if (pageIndex <= 0) pageIndex = 1;
            var result = _postQueryService.Find(
                new PostQueryOption
                {
                    SectionId = sectionId,
                    AuthorId = authorId,
                    PageInfo = new PageInfo(pageIndex)
                });

            ViewBag.Section = _sectionQueryService.FindInculdeStatisticById(sectionId).ToViewModel(sectionId);
            ViewBag.SectionId = sectionId;
            ViewBag.AuthorId = authorId;
            ViewBag.Pager = Pager.Items(result.TotalCount).PerPage(20).Move(pageIndex).Segment(5).Center();
            return View(result.Posts.Select(x => x.ToListViewModel()));
        }
        [HttpGet]
        public ActionResult Detail(string id)
        {
            var currentAccount = _contextService.GetCurrentAccount(HttpContext);
            ViewBag.CurrentAccountId = currentAccount?.AccountId;
            return View(_postQueryService.Find(id).ToDetailViewModel());
        }
        [HttpGet]
        public ActionResult Find(string id, string option)
        {
            return Json(new
            {
                success = true,
                data = _postQueryService.FindDynamic(id, option)
            });
        }
        [HttpGet]
        public ActionResult Create(string sectionId)
        {
            var section = _sectionQueryService.FindInculdeStatisticById(sectionId).ToViewModel(sectionId);
            return View(new PostDetailModel()
            {
                SectionId = section.Id,
                SectionName = section.Name
            });
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreatePostModel model)
        {
            var currentAccount = _contextService.GetCurrentAccount(HttpContext);
            var result = await _commandService.ExecuteAsync(
                new CreatePostCommand(
                    ObjectId.GenerateNewStringId(),
                    model.Subject,
                    model.Body,
                    model.SectionId,
                    currentAccount.AccountId));

            if (result.Status != AsyncTaskStatus.Success)
            {
                return Json(new { success = false, errorMsg = result.ErrorMessage });
            }
            var commandResult = result.Data;
            if (commandResult.Status == CommandStatus.Failed)
            {
                return Json(new { success = false, errorMsg = commandResult.Result });
            }

            return Json(new { success = true });
        }
        [HttpGet]
        public ActionResult Update(string id)
        {
            var model = _postQueryService.Find(id).ToDetailViewModel();
            return View(model);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(EditPostModel model)
        {
            var currentAccount = _contextService.GetCurrentAccount(HttpContext);
            if (model.AuthorId != currentAccount.AccountId)
            {
                return Json(new { success = false, errorMsg = "您不是帖子的作者，不能编辑该帖子。" });
            }

            var result = await _commandService.ExecuteAsync(new UpdatePostCommand(model.Id, model.Subject, model.Body));

            if (result.Status != AsyncTaskStatus.Success)
            {
                return Json(new { success = false, errorMsg = result.ErrorMessage });
            }
            var commandResult = result.Data;
            if (commandResult.Status == CommandStatus.Failed)
            {
                return Json(new { success = false, errorMsg = commandResult.Result });
            }

            return Json(new { success = true });
        }
    }
}

Forum.Web/Controllers/ReplyController.cs
using System.Threading.Tasks;
using ECommon.IO;
using ECommon.Utilities;
using ENode.Commanding;
using Forum.Commands.Replies;
using Forum.QueryServices;
using Forum.Web.Models;
using Forum.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Forum.Web.Controllers
{
    public class ReplyController : Controller
    {
        private readonly ICommandService _commandService;
        private readonly IContextService _contextService;
        private readonly IReplyQueryService _queryService;

        public ReplyController(ICommandService commandService, IContextService contextService, IReplyQueryService queryService)
        {
            _commandService = commandService;
            _contextService = contextService;
            _queryService = queryService;
        }

        [HttpGet]
        public ActionResult Find(string id, string option)
        {
            return Json(new
            {
                success = true,
                data = _queryService.FindDynamic(id, option)
            });
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateReplyModel model)
        {
            var currentAccount = _contextService.GetCurrentAccount(HttpContext);
            var result = await _commandService.ExecuteAsync(
                new CreateReplyCommand(
                    ObjectId.GenerateNewStringId(),
                    model.PostId,
                    model.ParentId,
                    model.Body,
                    currentAccount.AccountId), CommandReturnType.EventHandled);

            if (result.Status != AsyncTaskStatus.Success)
            {
                return Json(new { success = false, errorMsg = result.ErrorMessage });
            }
            var commandResult = result.Data;
            if (commandResult.Status == CommandStatus.Failed)
            {
                return Json(new { success = false, errorMsg = commandResult.Result });
            }

            return Json(new { success = true });
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(EditReplyModel model)
        {
            var currentAccount = _contextService.GetCurrentAccount(HttpContext);
            if (model.AuthorId != currentAccount.AccountId)
            {
                return Json(new { success = false, errorMsg = "您不是回复的作者，不能编辑该回复。" });
            }

            var result = await _commandService.ExecuteAsync(new ChangeReplyBodyCommand(model.Id, model.Body));

            if (result.Status != AsyncTaskStatus.Success)
            {
                return Json(new { success = false, errorMsg = result.ErrorMessage });
            }
            var commandResult = result.Data;
            if (commandResult.Status == CommandStatus.Failed)
            {
                return Json(new { success = false, errorMsg = commandResult.Result });
            }

            return Json(new { success = true });
        }
    }
}

Forum.Web/Views/Post/Create.cshtml
@using Microsoft.AspNetCore.Http.Extensions;

@model Forum.Web.Models.PostDetailModel
@{
    ViewBag.Title = "ENode论坛-发表帖子";
}
<environment include="Development">
    <link rel="stylesheet" href="~/lib/simditor-2.3.6/styles/simditor.css" />
</environment>
@Html.Partial("_BreadcrupbPartial", new List<Tuple<string, string>>()
{
    new Tuple<string, string>("/post/index?sectionId="+Model.SectionId,Model.SectionName),
    new Tuple<string, string>(Context.Request.GetDisplayUrl(),"发帖")
})

<div class="ibox-content">
    @using (Html.BeginForm("Create", "Post", FormMethod.Post, new
    {
        @class = "form-horizontal",
        @style = "margin: 0 90px",
        @id = "form"
    }))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_CreateOrUpdate", Model)
        <div class="form-group">
            <div class="">
                <button class="btn btn-primary btn-lg" type="button" onclick="submitForm()">提交帖子</button>
                <a class="btn btn-primary btn-lg" href="javascript:document.referrer?location.href=document.referrer:history.go(-1);">返回</a>
            </div>
        </div>
    }
</div>

@section Script{
    <environment include="Development">
        <script src="~/lib/simditor-2.3.6/scripts/module.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/uploader.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/hotkeys.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/simditor.js"></script>
    </environment>
    <script>
        function submitForm() {
            com.submitForm({
                $form: $("#form"),
                headers: { "RequestVerificationToken": $("input[name='__RequestVerificationToken']").val() },
                success: function(result) {
                    if (result.success) {
                        var href = '/post/index?sectionId=@Model.SectionId';
                        toastr.success('发帖成功!点击马上跳转!', null, {
                            timeOut: 2000,
                            progressBar: true,
                            onHidden: function() { location.href = href; },
                            onclick: function() { location.href = href; }
                        });
                    } else {
                        toastr.error(result.errorMsg);
                    }
                },
                error: function (result) { toastr.error(result.responseJSON.errorMsg); }
            });
        }
    </script>
}

Forum.Web/Views/Post/Detail.cshtml
@using Microsoft.AspNetCore.Http.Extensions;
@using Microsoft.AspNetCore.Html;

@model Forum.Web.Models.PostDetailModel
@{
    ViewBag.Title = "ENode论坛-帖子详情";
}
<environment include="Development">
    <link rel="stylesheet" href="~/lib/simditor-2.3.6/styles/simditor.css" />
</environment>
@Html.Partial("_BreadcrupbPartial", new List<Tuple<string, string>>()
{
    new Tuple<string, string>("/post/index?sectionId="+Model.SectionId,Model.SectionName),
    new Tuple<string, string>(Context.Request.GetDisplayUrl(),Model.Subject)
})

<div class="ibox-content">

    <div class="pull-left">
        <span>#楼主</span>
        <span style="margin-right: 5px">@Model.CreatedOn</span>
        @if (!string.IsNullOrEmpty(Model.AuthorName))
        {
            @Html.ActionLink(Model.AuthorName, "index", new { authorId = Model.AuthorId })
        }
    </div>

    <div class="pull-right">
        @if (Model.AuthorId == ViewBag.CurrentAccountId)
        {
            @Html.ActionLink("编辑", "Update", "Post", new
            {
                id = Model.Id
            }, new { @class = "btn btn-default btn-xs" })
        }
        @if (User.Identity.IsAuthenticated)
        {
            <button type="button" class="btn btn-primary btn-xs" onclick="reply.show('New')">回复</button>
        }
    </div>

    <div class="article-title">
        <h1>
            @(new HtmlString(Model.Subject))
        </h1>
    </div>

    @Html.Raw(Model.Body)

    <hr>

    @if (Model.Replies != null && Model.Replies.Any())
    {
        <div class="row">
            <div class="col-lg-12">
                @foreach (var reply in Model.Replies)
                {
                    <div class="social-feed-box">
                        <div class="social-avatar ">
                            <div class="media-body ">
                                <div class="pull-left">
                                    <span>#@reply.Floor@Html.Raw("楼")</span>
                                    @if (@reply.AuthorId == Model.AuthorId)
                                    {
                                        <span>[楼主]</span>
                                    }
                                    <small class="text-muted">@reply.CreatedOn</small>
                                    @if (!string.IsNullOrEmpty(reply.AuthorName))
                                    {
                                        @Html.ActionLink(reply.AuthorName, "index", new
                                        {
                                            authorId = reply.AuthorId
                                        })
                                    }
                                </div>
                                <div class="pull-right">
                                    @if (reply.AuthorId == ViewBag.CurrentAccountId)
                                    {
                                        <button type="button"
                                                class="btn btn-primary btn-xs"
                                                onclick="reply.show('Edit','@reply.Id')">编辑</button>
                                    }
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <button type="button" 
                                                class="btn btn-primary btn-xs" 
                                                onclick="reply.show('NewSub','@reply.Id')">回复</button>
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="social-body">
                            @Html.Raw(reply.Body)
                        </div>
                    </div>
                }
            </div>
        </div>
        <hr>
    }

    <div class="row" id="reply">
        <div class="col-lg-12">
            @using (Html.BeginForm("Create", "Reply", FormMethod.Post, new { @id = "form", @style = "display:none" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("PostId", Model.Id)
                @Html.Hidden("Id")
                @Html.Hidden("ParentId")
                @Html.Hidden("AuthorId")
                <div class="form-group">
                    <textarea autofocus="" cols="20"
                              id="Body" name="Body"
                              placeholder="这里输入内容" 
                              rows="2" 
                              style="height: 100px;"></textarea>
                </div>
                <div class="form-group">
                    <div class="">
                        <button class="btn btn-primary btn-lg"
                                type="button"
                                onclick="reply.submit()" id="button"></button>
                    </div>
                </div>
            }
        </div>
    </div>

</div>

@section Script{
    <environment include="Development">
        <script src="~/lib/simditor-2.3.6/scripts/module.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/uploader.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/hotkeys.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/simditor.js"></script>
    </environment>

    <script>

        var reply = (function ($, com) {
            var FormModel = function ($form) {
                this.$form = $form;
                this.$postId = $form.find('#PostId');
                this.$button = $form.find('#button');
                this.method = '';
                this.$replyId = $form.find('#Id');;
                this.$parentId = $form.find('#ParentId');;
                this.$authorId = $form.find('#AuthorId');;
                this.$body = $form.find('#Body');
                this.editor = new Simditor({
                    toolbarFloatOffset: 1,
                    textarea: this.$body
                });
                /***
                * 清空表单内容
                */
                this.clear = function () {
                    this.$replyId.val('');
                    this.$parentId.val('');
                    this.$authorId.val('');
                    this.$body.val('');
                    if (this.editor.getValue()) {
                        if (confirm('是否清空当前回复内容?')) {
                            this.editor.setValue('');
                        }
                    }
                }
                /***
                * 提交
                */
                this.submit = function () {
                    if (this.method) {
                        var url = '';
                        var msg = '';
                        switch (this.method) {
                            case 'NewSub':
                            case 'New':
                                url = '/Reply/Create';
                                msg = '发表回复成功!点击马上跳转!';
                                break;
                            case 'Edit':
                                url = '/Reply/Update';
                                msg = '编辑回复成功!点击马上跳转!';
                                break;
                        }
                        com.submitForm({
                            url: url,
                            $form: $form,
                            headers: { "RequestVerificationToken": $("input[name='__RequestVerificationToken']").val() },
                            success: function (result) {
                                if (result.success) {
                                    var href = '@Context.Request.GetDisplayUrl()';
                                    toastr.success(msg, null, {
                                        timeOut: 2000,
                                        progressBar: true,
                                        onHidden: function () { location.href = href; },
                                        onclick: function () { location.href = href; }
                                    });
                                } else {
                                    toastr.error(result.errorMsg);
                                }
                            },
                            error: function(result) { toastr.error(result.responseJSON.errorMsg); }
                        });
                    } else {
                        alert('未指定提交地址');
                    }
                }
                /***
                * 显示
                */
                this.show = function (arguments) {
                    switch (arguments[0]) {
                        case 'NewSub':
                            if (arguments[1]) { this.$parentId.val(arguments[1]); }
                            this.method = 'NewSub';
                            this.$button.text('发表回复');
                            break;
                        case 'New':
                            this.method = 'New';
                            this.$button.text('发表回复');
                            break;
                        case 'Edit':
                            this.method = 'Edit';
                            this.$button.text('修改回复');
                            if (arguments[1]) {
                                var $replyId = this.$replyId;
                                var $parentId = this.$parentId;
                                var $authorId = this.$authorId;
                                var editor = this.editor;
                                $.ajax({
                                    data: { id: arguments[1], option: 'simple', random: Math.random() },
                                    url: '/reply/find',
                                    type: "GET",
                                    beforeSubmit: function () { },
                                    beforeSend: function (a, b, c) { },
                                    complete: function () { },
                                    success: function (result) {
                                        if (result.success) {
                                            $replyId.val(result.data.id);
                                            $parentId.val(result.data.parentId);
                                            $authorId.val(result.data.authorId);
                                            editor.setValue(result.data.body);
                                        } else {
                                            toastr.error(result.errorMsg);
                                        }
                                    }
                                });
                            }
                            break;
                    }
                    $form.css("display", "block");
                }
                /***
                * 跳转到锚点
                */
                this.jump = function () {
                    location.hash = '#' + $form[0].id;
                    window.location = window.location;
                }
            }
            var model = new FormModel($('#form'));

            /***
            * 显示回复框
            */
            function show() {
                model.clear();
                model.show(arguments);
                model.jump();
            }

            /***
            * 提交回复
            */
            function submit() { model.submit(); }

            return {
                show: show,
                submit: submit
            }
        })($, com);

    </script>
}

Forum.Web/Views/Post/Index.cshtml
@using Forum.Web.Models
@model IEnumerable<PostListModel>
@{
    ViewBag.Title = "ENode论坛-帖子列表";
    var sectionModel = ViewBag.Section as SectionAndStatisticModel;
}
@if (sectionModel.IsActive)
{
    @Html.Partial("_BreadcrupbPartial", new List<Tuple<string, string>>()
    {
        new Tuple<string, string>("/post/index?sectionId="+sectionModel.Id,sectionModel.Name)
    })
}
else
{
    @Html.Partial("_BreadcrupbPartial", new List<Tuple<string, string>>())
}

<div class="ibox-content forum-container">
    @if (sectionModel.IsActive)
    {
        <div class="forum-title">
            <div class="row">
                <div class="pull-right forum-desc">
                    <samll>总帖子数： @sectionModel.PostCount</samll>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <a href="/post/create?sectionId=@sectionModel.Id" class="btn btn-info ">
                        <i class="fa fa-pencil-square-o"></i> 发帖
                    </a>
                }
            </div>
        </div>
    }
    else
    {
        <div class="forum-title">
            <div class="row">
                <a href="javascript:history.go(-1);" class="btn btn-info ">
                    <i class="fa fa-pencil-square-o"></i> 返回
                </a>
            </div>
        </div>
    }

    <div class="forum-item">
        <div class="row">
            <div class="col-sm-7">
                <div>
                    <small>标题</small>
                </div>
            </div>
            <div class="col-sm-1 forum-info">
                <div>
                    <small>发帖人</small>
                </div>
            </div>
            <div class="col-sm-1 forum-info">
                <div>
                    <small>发帖时间</small>
                </div>
            </div>
            <div class="col-sm-1 forum-info">
                <div>
                    <small>更新时间</small>
                </div>
            </div>
            <div class="col-sm-1 forum-info">
                <div>
                    <small>回复数</small>
                </div>
            </div>
            <div class="col-sm-1 forum-info">
                <div>
                    <small>回复人</small>
                </div>
            </div>
        </div>
    </div>

    @foreach (var post in Model)
    {
        <div class="forum-item">
            <div class="row">
                <div class="col-sm-7">
                    <div class="forum-icon">
                        <i class="fa fa-bookmark"></i>
                    </div>
                    @Html.ActionLink(post.Subject, "detail"
                        , new { id = post.Id }, new
                        {
                            @class = "forum-item-title",
                            //target = "_blank"
                        })
                </div>
                <div class="col-sm-1 forum-info">
                    <span class="views-number">
                        @Html.ActionLink(post.AuthorName, "index", new { authorId = post.AuthorId })
                    </span>
                </div>
                <div class="col-sm-1 forum-info">
                    <span class="views-number">
                        @post.CreatedOn
                    </span>
                </div>
                <div class="col-sm-1 forum-info">
                    <span class="views-number">
                        @post.LastUpdateTime
                    </span>
                </div>
                <div class="col-sm-1 forum-info">
                    <span class="views-number">
                        @post.ReplyCount
                    </span>
                </div>
                <div class="col-sm-1 forum-info">
                    <span class="views-number">
                        @if (post.MostRecentReply != null)
                        {
                            @Html.ActionLink(post.MostRecentReply.AuthorName, "index", new { authorId = post.MostRecentReply.AuthorId })
                        }
                        else
                        {
                            @Html.Raw("-")
                        }
                    </span>
                </div>
            </div>
        </div>
    }

    <div class="pagination pull-right ">
        @{
            Forum.Web.Controls.Pager pager = ViewBag.Pager;
            string authorId = ViewBag.AuthorId;
            string sectionId = ViewBag.SectionId;

            if (pager.HasPreviousPage)
            {
                <li>@Html.ActionLink("<<", "index", new { authorId = authorId, sectionId = sectionId, page = pager.FirstPageIndex })</li>
                <li>@Html.ActionLink("<", "index", new { authorId = authorId, sectionId = sectionId, page = pager.PreviousPageIndex })</li>
            }

            foreach (int page in ViewBag.Pager)
            {
                <li>@Html.ActionLink(page.ToString(), "index", new { authorId = authorId, sectionId = sectionId, page = page })</li>
            }

            if (pager.HasNextPage)
            {
                <li>@Html.ActionLink(">", "index", new { authorId = authorId, sectionId = sectionId, page = pager.NextPageIndex })</li>
                <li>@Html.ActionLink(">>", "index", new { authorId = authorId, sectionId = sectionId, page = pager.LastPageIndex })</li>
            }
        }
    </div>
    <div class="clearfix"></div>

</div>

Forum.Web/Views/Post/Update.cshtml
@using Microsoft.AspNetCore.Http.Extensions;

@model Forum.Web.Models.PostDetailModel
@{
    ViewBag.Title = "ENode论坛-修改帖子";
}
<environment include="Development">
    <link rel="stylesheet" href="~/lib/simditor-2.3.6/styles/simditor.css" />
</environment>
@Html.Partial("_BreadcrupbPartial", new List<Tuple<string, string>>()
{
    new Tuple<string, string>("/post/index?sectionId="+Model.SectionId,Model.SectionName),
    new Tuple<string, string>("/post/detail?id="+Model.Id,Model.Subject),
    new Tuple<string, string>(Context.Request.GetDisplayUrl(),"修改帖子")
})

<div class="ibox-content">
    @using (Html.BeginForm("Update", "Post", FormMethod.Post, new
    {
        @class = "form-horizontal",
        @style = "margin: 0 90px",
        @id = "form"
    }))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_CreateOrUpdate", Model)
        <div class="form-group">
            <div class="">
                <button class="btn btn-primary btn-lg" type="button" onclick="submitForm()">提交修改</button>
                <a class="btn btn-primary btn-lg" href="javascript:document.referrer?location.href=document.referrer:history.go(-1);">返回</a>
            </div>
        </div>
    }
</div>

@section Script{
    <environment include="Development">
        <script src="~/lib/simditor-2.3.6/scripts/module.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/uploader.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/hotkeys.js"></script>
        <script src="~/lib/simditor-2.3.6/scripts/simditor.js"></script>
    </environment>
    <script>
        function submitForm() {
            com.submitForm({
                $form: $("#form"),
                headers: { "RequestVerificationToken": $("input[name='__RequestVerificationToken']").val() },
                success: function (result) {
                    if (result.success) {
                        var href = '/post/detail?id=@Model.Id';
                        toastr.success('修改帖子成功!点击马上跳转!', null, {
                            timeOut: 2000,
                            progressBar: true,
                            onHidden: function () { location.href = href; },
                            onclick: function () { location.href = href; }
                        });
                    } else {
                        toastr.error(result.errorMsg);
                    }
                },
                error: function (result) { toastr.error(result.responseJSON.errorMsg); }
            });
        }
    </script>
}

Forum.Web/Views/Post/_CreateOrUpdate.cshtml
@model Forum.Web.Models.PostDetailModel

@Html.HiddenFor(model => model.SectionId)
@Html.HiddenFor(model => model.AuthorId)
@Html.HiddenFor(model => model.AuthorName)
<div class="form-group">
    <label class=" control-label">主题</label>
    @Html.TextBoxFor(model => model.Subject
    , new
    {
        @class = "form-control help-block m-b-none"
    })
</div>
<div class="form-group">
    @Html.TextAreaFor(model => model.Body
    , new
    {
        @placeholder = "这里输入内容",
        @autofocus = ""
    })
</div>

<script>
    window.onload =function () {
        var editor = new Simditor({
            toolbar: ['title', 'bold', 'italic', 'underline', 'strikethrough', 'fontScale', 'color', '|', 'ol', 'ul', 'blockquote', 'code', 'table', '|', 'link', 'image', 'hr', '|', 'indent', 'outdent', 'alignment'],
            textarea: $('#Body')
        });
    };
</script>